name: Auto-Tag on Merge

on:
  push:
    branches: [staging]

jobs:
  tag:
    uses: sonarmd/workflows/.github/workflows/tag-release.yml@main
    with:
      repo-short: fe
      environment: stg
    permissions:
      contents: write
