name: Auto-Tag Release

on:
  push:
    branches: [staging]

permissions: {}

jobs:
  tag:
    permissions:
      contents: write
    uses: sonarmd/workflows/.github/workflows/tag-release.yml@main
    with:
      repo-short: mobile
      environment: stg
